version: '3.9'

services:
  battleship-api:
    image: rogerbu/battleship-api
    build:
      context: ./battleship-api
    container_name: battleship-api
    restart: always
    depends_on:
      - kafka1
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://battleship-api:8080/battleship-service/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 200
    environment:
      TZ: GMT+1
      SPRING.PROFILE: prod
      SPRING.KAFKA.BOOTSTRAP-SERVERS: kafka1:9092
      SPRING.KAFKA.CONSUMER.GROUP-ID: battleship
    expose:
      - 8080
    networks:
      - battle-network

  battleship-async:
    image: battleship-async/battleship_api
    build:
      context: ./battleship-async
    container_name: battleship-async
    restart: always
    depends_on:
      - kafka1
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://battleship-async:8081/battleship-service/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 200
    environment:
      TZ: GMT+1
      SPRING.PROFILE: prod
      SPRING.KAFKA.BOOTSTRAP-SERVERS: kafka1:9092
      SPRING.KAFKA.CONSUMER.GROUP-ID: battleship
      GAME.SERVER_FEIGN: http://battleship-api:8080
    expose:
      - 8081
    networks:
      - battle-network

  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - battle-network
  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    depends_on:
      - zookeeper1
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - 29092
      - 9092
    networks:
      - battle-network

networks:
  battle-network:
    driver: bridge