server:
  port: 8081
  servlet:
    context-path: /battleship-service

spring:
  profiles:
    active: prod

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    consumer:
      group-id: battleship
game:
  server_feign: http://localhost:8080
topics:
  gamenew: battleship.game.new
  gamefieldfire: battleship.game.field.fire
