name: Battle-Ship-Continuous Integrations with Java Spring and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Java JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: 'adopt' 
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Build with Docker Compose
        run: docker compose build

      - name: Push to Docker Hub registry
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/battle-ship:latest ${{secrets.DOCKER_USERNAME}}/battle-ship:${{github.runn_id}} 
          
          docker push ${{secrets.DOCKER_USERNAME}}/battle-ship:${{github.runn_id}}

